# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fQwa_K45HOSoUfadQ1BW9gTqbtQ75Wx8
"""

import pandas as pd
import numpy as np
import pickle
import os
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Load datasets
fake = pd.read_csv('Fake.csv', engine='python', on_bad_lines='skip')
true = pd.read_csv('True.csv', engine='python', on_bad_lines='skip')

# Add labels
fake['label'] = 0
true['label'] = 1

# Combine datasets
data = pd.concat([fake, true])

# Shuffle
data = data.sample(frac=1)

# Select features
X = data['text']
y = data['label']

# Convert text to vectors
vectorizer = TfidfVectorizer(stop_words='english', max_df=0.7)
X = vectorizer.fit_transform(X)

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Train model
model = LogisticRegression()
model.fit(X_train, y_train)

# Accuracy
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

# Create directory if it doesn't exist
os.makedirs('model', exist_ok=True)

# Save model
with open('model/fake_news_model.pkl', 'wb') as f:
    pickle.dump((model, vectorizer), f)

print("Model saved!")

import pickle

# Load model
with open('model/fake_news_model.pkl', 'rb') as f:
    model, vectorizer = pickle.load(f)

def predict_news(news):
    data = vectorizer.transform([news])
    prediction = model.predict(data)

    if prediction[0] == 0:
        return "Fake News ❌"
    else:
        return "Real News ✅"

# Test input
if __name__ == "__main__":
    print("Enter news text:")
    user_input = input()
    result = predict_news(user_input)
    print("Result:", result)